### ISSUE TITLE
[Feature request] Make it use any gyro available

### ISSUE THREAD

**Issue by Kabouik** [iVideoGameBoss/PhoenixHeadTracker#3]
I ordered my Nreal Air glasses exactly for this, before I knew your program existed already, just in hope that this would be possible one day! So thanks a lot!

I have not received them yet, but in the mean time, when playing MSFS2020 on a handheld device that has a gyro, I was able to use it as a freelook input. See it here in action: https://youtu.be/DtOXas-GK-0?t=147

While this works nicely, it uses some program from the handheld brand to convert the gyro data to cursor moves, and then some in-game options. I feel your program would be more generic and may not need the in-game settings. Even if it does, I'd still prefer using it over some closed-source software from the manufacturer.

What do you think about adding a way to select the device instead of hardcoded Nreal sensors?

**Comment by iVideoGameBoss** [comment]
I released a new version that also works with opentrack UDP. https://youtu.be/-dKAtpcpRZ4

**Comment by Kabouik** [comment]
Nice, and really impressivde in MSFS. Do you think it would be hard to extend that to any 3-dof data from any device? I'm thinking this would be useful for handhelds. 

Mine is a  GPD Win 4, and GPD provides some way to convert gyro data into curspr position. but it's closed source and not generic to all handhelds.

**Comment by iVideoGameBoss** [comment]
As long as you have access to a DLL file that can output Euler angles in degrees or radians you can make the software work. Its just a matter of feeding data to it from gyro. Since I made it open source anyone should be able to make it work with any device.
