### ISSUE TITLE
[Enhancement] Linux Build

### ISSUE THREAD

**Issue by ZaxLofful** [iVideoGameBoss/PhoenixHeadTracker#6]
I want to be able to use this natively in Linux, since I do all my gaming on Linux these days.

Where did you get the DLL that you are using to receive the sensor data?

**Comment by iVideoGameBoss** [comment]
I got the dll from here https://github.com/MSmithDev/AirAPI_Windows

You should be able to run PhoenixHeadTracker using proton. I have seen a few people say they got it all working on steam deck which I believe uses Arch Linux

**Comment by Kabouik** [comment]
> I want to be able to use this natively in Linux, since I do all my gaming on Linux these days.
> 
> Where did you get the DLL that you are using to receive the sensor data?

Have you managed? I'd be interested in using a Linux build too.
